#!/usr/bin/python 

import socket, sys, select, argparse, urllib.request, os.path, subprocess, json, fcntl

def readLine(sock):
	l = b""
	while True:
		c = sock.recv(1)
		if c == b"\n":
			yield l.decode('utf-8')
			l = b""
		elif c == "":
			raise StopIteration
		else:
			l += c

def preprocess(code, no_coffee):
	if not no_coffee:
		return subprocess.Popen(["coffee", "-cs"], stdin=subprocess.PIPE, stdout=subprocess.PIPE).communicate(code)[0] + b"\n"
	else:
		return code + b"\n"

p = argparse.ArgumentParser(description = 'Execute javascript in your browser')
p.add_argument("instance", nargs = '?', default = None, help = "Instance in which javascript will be executed")
p.add_argument("args", nargs = '*', default = [], help = "Arguments to pass to the script (JSON formatted)")
p.add_argument("--list", "-l", help = "List instances", action = "store_true")
p.add_argument("--file", "-f", help = "File to execute (- is for STDIN)", default = [], action = "append")
p.add_argument("--include", "-i", help = "Same as -f, but never pre-processed by coffee-script", default = [], action = "append")
p.add_argument("--execute", "-e", help = "Execute given javascript argument", default = [], action = "append")
p.add_argument("--no-coffee", "-c", help = "Don't try to use coffee-script to preprocess the javascript", action = "store_true")
p.add_argument("--no-jquery", "-j", help = "Don't prepend jQuery to the script", action = "store_true")
p.add_argument("--no-close", "-n", help = "Don't ask to close connection after transmitting the script", action = "store_true")
args = p.parse_args()

newargs = []
for a in args.args:
	try:
		json.loads(a)
		newargs.append(a)
	except:
		newargs.append(json.dumps(a))
args.args = newargs

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('localhost', 12346))

# Find instances list
s.sendall(b"LIST\n")
browsers = []
instances = []
for line in readLine(s):
	if line == "":
		break
	bid = line.split()[0]
	browsers.append(bid)

	s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s2.connect(('localhost', 12346))
	s2.sendall(("TUNNEL " + bid + "\n").encode('utf-8'))
	s2.sendall(b"LIST\n")
	for line in readLine(s2):
		if line == "":
			break
		active = False
		if line.startswith('* '):
			active = True
			line = line[2:]
		line = line.split(" ", 2)
		instances.append((active, bid + ":" + line[0], line[1], line[2]))
	s2.sendall(b"CLOSE\n")

# Handle --list
if args.list:
	for instance in instances:
		if instance[0]:
			print('[', end="")
		print("%s: (%s) %s" % (instance[1], instance[2], instance[3]), end="")
		if instance[0]:
			print(']', end="")
		print()
	sys.exit(0)

# Find instance
if args.instance is None or args.instance == ".":
	for instance in instances:
		if instance[0]:
			args.instance = instance[1]
			break
else:
	found = False
	path = args.instance.strip(":").split(":")
	for instance in instances:
		if instance[1].split(":")[-len(path):] == path:
			args.instance = instance[1]
			found = True
			break
	if not found:
		for instance in instances:
			if args.instance in instance[2] + " " + instance[3]:
				found = True
				args.instance = instance[1]
				if instance[0]:
					break
		if not found:
			print("Can't find instance")
			sys.exit(1)

# Find code
code = b""
has_stdin = True
if not args.include and not args.execute and not args.file:
	args.file = ["-"]

# 1. Include files (-i)
for i in args.include:
	if i == "-":
		has_stdin = False
		code += sys.stdin.read().encode('utf-8') + b"\n"
	else:
		code += open(i, 'rb').read() + b"\n"

# 2. Files (-f)
for f in args.file:
	if f == "-":
		has_stdin = False
		code += preprocess(sys.stdin.read().encode('utf-8'), args.no_coffee)
	else:
		code += preprocess(open(f, 'rb').read(), args.no_coffee)

# 3. Command-line (-e)
for e in args.execute:
	code += preprocess(e.encode('utf-8'), args.no_coffee)

code = b"args = [" + ",".join(args.args).encode('utf-8') + b"];\n" + code

# Prepend jquery to the script
if not args.no_jquery:
	jquery_path = os.path.expanduser("~/.cache/jquery.min.js")
	if os.path.exists(jquery_path):
		jquery = open(jquery_path).read().encode('utf-8')
	else:
		jquery = urllib.request.urlopen("http://code.jquery.com/jquery.min.js").read()
	code = jquery + b"\n" + code

# Eval code
bid, inst = args.instance.rsplit(":", 1)
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('localhost', 12346))
s.sendall(b"TUNNEL " + bid.encode('utf-8') + b"\n")
s.sendall(b"EVAL " + str(len(code)).encode('utf-8') + b" " + str(inst).encode('utf-8') + b"\n")
s.sendall(code)
if not args.no_close:
	s.sendall(b"CLOSE\n")

p = select.epoll()
p.register(s, select.EPOLLIN)
if has_stdin and args.no_close:
	fcntl.fcntl(0, fcntl.F_SETFL, fcntl.fcntl(0, fcntl.F_GETFL) | os.O_NONBLOCK)
	p.register(0, select.EPOLLIN)

# Redirect stdin to script, and script output to stdout
while True:
	try:
		fd, event = p.poll(-1, 1)[0]
	except KeyboardInterrupt:
		s.close()
		sys.exit(0)
	if fd == 0:
		data = sys.stdin.read(1024).encode('utf-8')
		if data:
			s.sendall(data)
		else:
			s.sendall(b"CLOSE\n")
			p.unregister(fd)
	else:
		data = s.recv(1024)
		if data:
			os.write(1, data)
		else:
			break
